# Calamares Welcome Module Configuration
---
showSupportUrl: true
showKnownIssuesUrl: true
showReleaseNotesUrl: true
showWebUrl: true

requirements:
    requiredStorage: 15
    requiredRAM: 2.0
    internetCheckUrl: http://ping.archlinux.org
    check:
        - storage
        - ram
        - power
        - internet
        - root
    required:
        - storage
        - ram
