[Theme]
Name=Yumemiro-Glass
Description=Yumemiro OS Glassmorphic SDDM Theme
Author=Yumemiro Team
License=GPL
Type=sddm-theme
Version=1.0

[General]
background=backgrounds/default.jpg
font="Inter"
fontSize=11
backgroundMode=aspect
panelColor="rgba(28, 20, 42, 0.75)"
accentColor="#f472b6"
textColor="#f3e8ff"
roundness=24
